### ISSUE TITLE
[v2] Regression in validation of FieldArray after change

### ISSUE THREAD

**Issue by simoneb** [jaredpalmer/formik#1941]
### Current Behavior

Validation is not run after I [`push`](https://jaredpalmer.com/formik/docs/api/fieldarray#fieldarray-helpers) an item to the array.

### Expected behavior

In version 1.x, validation was run right away.

### Reproducible example

https://codesandbox.io/s/formik-v2-fieldarray-validation-repro-hrqqj

The repro is using Formik v2. You will see that adding new items by clicking the button doesn't trigger validation.

If you downgrade to Formik 1.x you will see that adding an item will trigger validation.

### Suggested solution(s)

Revert to the previous behavior or document the breaking change.

**Comment by fenech** [comment]
Here's another reproducible example using the `validate` props: https://codesandbox.io/s/ecstatic-swanson-tz1ih

It looks like the issue is that the second argument to `setFormikState` (the callback) is never called. https://github.com/jaredpalmer/formik/blob/master/src/FieldArray.tsx#L169

This is because `setFormikState` only takes one argument. https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L664.

The following test fails:
```tsx
    it('should validate form after adding the value', async () => {
      let arrayHelpers: any;
      let validate = jest.fn();
      let form = (
        <TestForm validate={validate}>
          <FieldArray
            name="friends"
            render={arrayProps => {
              arrayHelpers = arrayProps;
              return null;
            }}
          />
        </TestForm>
      );

      let { rerender } = render(form);
      arrayHelpers.push('tom');
      rerender(form);
      await wait(() => {
        expect(validate).toHaveBeenCalled();
      });
    });
```

**Comment by jrobeson** [comment]
why not submit the failing test as a PR?

**Comment by schreyerpeter** [comment]
I'm experiencing the same issue with validation not running after calling `replace` on an existing item in the field array.

I forked off your example, @simoneb 
https://codesandbox.io/s/formik-v2-fieldarray-validation-repro-eeylg

**Comment by jaredpalmer** [comment]
I believe this is fixed in 2.1

**Comment by simoneb** [comment]
@jaredpalmer the behavior has improved in 2.1.1 but it's not the same as it was in 1.x.

See the updated sandbox here: https://codesandbox.io/s/formik-v2-fieldarray-validation-repro-hrqqj

And the screenshots below. Notice that the 2.1.1 version is "falling one field behind". The when I add a new field to the array the previous ones are validated but not the newly added one, whereas in version 1.5.8 the form state was in sync and also the newly added field is being validated at the time it's added.

### 1.5.8

![formik-v2-fieldarray-validation-repro - CodeSandbox - Edited](https://user-images.githubusercontent.com/20181/71962203-473cb500-31f9-11ea-819b-bb77b65cc4eb.gif)

### 2.1.1

![formik-v2-fieldarray-validation-repro - CodeSandbox - Edited (1)](https://user-images.githubusercontent.com/20181/71962262-5f143900-31f9-11ea-87c1-c4c1ab766ab2.gif)

**Comment by gsaandy** [comment]
Looks like the validation is only triggering for `push`, but **not** for `replace` and `remove`

**Comment by pavelspichonak** [comment]
@simoneb Any updates?.. The issue is still reproducible

**Comment by simoneb** [comment]
@pavelspichonak it is still reproducible in 2.1.5. When a new field is added to a field array, its value is not validated. The behavior is the same as in 2.1.1. See screenshot below and [updated sandbox](https://codesandbox.io/s/formik-v2-fieldarray-validation-repro-hrqqj?file=/src/App.js).

![React App](https://user-images.githubusercontent.com/20181/91654196-2b975f00-eaa7-11ea-8a9e-3472f26a4f25.gif)
