### ISSUE TITLE
Typescript error when useing "useField" and "FieldAttributes"

### ISSUE THREAD

**Issue by Shaker-Hamdi** [jaredpalmer/formik#2127]
I updated Formik to "2.0.8" and I tried to use the new `useField` hook.
I followed a tutorial online by `Ben Awad`, but typescript is not happy and refuses to compile ...

![image](https://user-images.githubusercontent.com/3071511/70862544-720f5280-1f46-11ea-9b56-6586b30791e0.png)

![image](https://user-images.githubusercontent.com/3071511/70862595-0da0c300-1f47-11ea-9bf8-b3e35d8cf78b.png)

Here's my component ...

```
import React from "react";
import { useField, FieldAttributes } from "formik";

type MyRadioProps = { label: string } & FieldAttributes<{}>;

const MyRadio: React.FC<MyRadioProps> = ({ label, ...props }) => {
    const [field] = useField<{}>(props);

    return (
        <div>
            <label>{label}</label>
            <input type="radio" {...field} {...props} />
        </div>
    );
};

export default MyRadio;
```

I couldn't find any Typescript demos for useField.
The only demo I found was this ...
https://jaredpalmer.com/formik/docs/api/useField

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 2.0.8
| React            | 16.12.0
| TypeScript       | 3.7.3
| next   | 9.1.5
| Operating System | Windows

**Comment by Shaker-Hamdi** [comment]
Now when I do it like this, Typescript seems happy with it and works fine ...

```
import React from "react";
import { useField, FieldInputProps } from "formik";

interface MyRadioProps extends FieldInputProps<""> {
    label: string;
}

const MyRadio: React.FC<MyRadioProps> = ({ label, ...props }) => {
    const [field] = useField(props);

    return (
        <div>
            <label>{label}</label>
            <input type="radio" {...field} {...props} />
        </div>
    );
};

export default MyRadio;
```

I don't know if that is correct or not, but it works.

**Comment by lightwave** [comment]
This is related to #1961. I have a PR #2154 open for that.

**Comment by jaredpalmer** [comment]
Fixed in 2.1

**Comment by lifedup** [comment]
This is marked as solved but I'm using 2.1.4  and hit this issue.  Thanks @Shaker-Hamdi for the solution.  Just FYI it appears that you lose the ability to set some default input props like ID.  I had to add the input props too

```
interface HTMLFormGroup extends React.HTMLAttributes<HTMLInputElement> {
    label: string;
}

export const Input: React.FC<HTMLFormGroup & FieldInputProps<"">> = ({label, ...props}) => {
  //couldn't access props.id
};
```

**Comment by Barrego** [comment]
Still having this problem on 2.1.4

**Comment by mkdudeja** [comment]
Hi Team, @jaredpalmer @lightwave 

Still facing the issue.

I have latest version of formik installed.

My Type look like this:

```
type MyInputProps = FieldHookConfig<string> & {
    id: string,
    label: string
};
```

But, getting the same typescript error.

Any help would be appreciated.

**Comment by farah** [comment]
Any solution to this?

**Comment by ahmedosama5200** [comment]
Same here, too

**Comment by oliver-au** [comment]
> Hi Team, @jaredpalmer @lightwave
> 
> Still facing the issue.
> 
> I have latest version of formik installed.
> 
> My Type look like this:
> 
> ```
> type MyInputProps = FieldHookConfig<string> & {
>     id: string,
>     label: string
> };
> ```
> 
> But, getting the same typescript error.
> 
> Any help would be appreciated.

```
type BaseTextFieldProps = FieldHookConfig<string> & {
	label: string
};

const BaseTextField = (props: BaseTextFieldProps) => {
	const [field, meta, helpers] = useField(props);
	const {label, name, type } = props
	return (
		<>
			<TextField 
				{...field} 
				label={label} 
				name={name} 
				type={type} 
			/>
			
			{meta.touched && meta.error ? (
				<div className="error">{meta.error}</div>
			) : null}
		</>
	);
};
```

With the code from @mkdudeja 
Here is my solution, it works for me.

**Comment by bwyx** [comment]
I choose `JSX.IntrinsicElements['input']` since I will **only** spread props to HTML `input` Element. here is mine
```ts
type Props = JSX.IntrinsicElements['input'] & {
  label: string
  name: string
}
```

more:
```ts
type Props = JSX.IntrinsicElements['input'] & {
  label: string
  name: string
}

const TextInput = ({
  label,
  name,
  ...props
}: Props): JSX.Element => {
  const [field, meta] = useField(name)

  return (
    <label>
      <span>{label}</span>
      <input
        {...field}
        {...props}
      />
...
```

**Comment by batbrain9392** [comment]
I'm sure there can be a better Typescript-based solution to this.
