### ISSUE TITLE
FieldArray remove helper can set error state to empty array

### ISSUE THREAD

**Issue by TLadd** [jaredpalmer/formik#784]
## Current Behavior

When using FieldArray's remove helper, my errors state for the field gets set to an empty array for two renders. This is problematic if you are expecting errors to be an object with only string values.

[This line](https://github.com/jaredpalmer/formik/blob/master/src/FieldArray.tsx#L194) is what sets the errors state to an empty array, since the function is used both for the form state as well as the errors state.

## Steps to Reproduce

Use FieldArray with a populated array and call .remove() with an index. Log the errors state and observer that for two renders, the field has an empty array error state.

Here's an example codesandbox: https://codesandbox.io/s/p9x78o5zyq
If you open up the console and click the X button to remove one of the items in the array, you'll notice that errors.arr is set to an empty array for two logs before being reset by validate.

![Imgur](https://i.imgur.com/Xy9MFA6.png)

## Expected behavior

The arr field should not be present in the errors object for these cases

## Suggested solution(s)

Need a way to not default the error state to an empty array on remove. Seems like it might be necessary to change updateArrayField to allow for different logic when updating the error state rather than sharing the function that updates the form state.

**CodeSandbox Link**: https://codesandbox.io/s/p9x78o5zyq

---

- Formik Version: 1.0.1
- React Version: 16.4.1
- TypeScript Version: N/A
- Browser and Version: Chrome 67.0.3396.99
- OS: Mac OS X
- Node Version:N/A
- Package Manager and Version: N/A

**Comment by ersel** [comment]
This issue seem to occur on `formik@2.0.1-rc.5`

After removing a field with the `arrayHelper.remove`, `errors` object contains an empty array which makes `hasError` field return true as well.

**Comment by ersel** [comment]
As a temporary fix I ended up calling `validateForm` manually after a certain timeout.

**Comment by TLadd** [comment]
Yeah, after updating to `formik@2.0.1-rc.5`, it actually looks like now the empty array remains there, whereas before it would go away on subsequent renders.

Updated codesandbox: https://codesandbox.io/s/formik-example-uez7v

**Comment by 3nvi** [comment]
This should be re-opened as it's still happening on rc.13

**Comment by TLadd** [comment]
I was fine with this being closed because the error changed to be somewhat worse in the newer versions of Formik, and so I opened https://github.com/jaredpalmer/formik/issues/1616.

**Comment by samueldepooter** [comment]
> As a temporary fix I ended up calling `validateForm` manually after a certain timeout.
> 
> ```
> onClick={() => {
>   arrayHelpers.remove(index);
>   setTimeout(() => {
>     validateForm();
>   }, 200);
> }}
> ```

This was a good start but it causes a timeframe where an error does exist (and in my case that would show an error block for a split second).

For my use-case, which involves only validation on submit, I fixed it the following:
```
// get a copy of your old errors so that they're not reset
const errors = Object.assign({}, formikBag.errors);
// remove it (triggers the validation which causes the mentioned issue)
helpers.remove(field.index);
// set your errors back to your old errors
formikBag.setErrors(errors);
```

**Comment by klimashkin** [comment]
It also doesn't always make field touched as advertised.
Due to multiple bugs with FieldArray it's easier to explicitly use setFieldTouched/setTouched and setFiledValue/setValue

**Comment by seamuslowry** [comment]
Was this closed by https://github.com/jaredpalmer/formik/pull/2115?

**Comment by alex-sh-li** [comment]
had the same problem on 2.0.6, upgraded to 2.2.0 problem still existed.
